services:
  ktor:
    image: leocare/ktor-api-miscuentas:0.1.0
    build: .
    platform: linux/amd64
    container_name: ktor_api_rest
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - .env
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge